live_config_reload = true
window_opacity = 0.97

[cursor]
style = "Block"
unfocused_hollow = true

[font]
draw_bold_text_with_bright_colors = true
size = 12.0

[font.bold]
family = "SauceCodePro NF"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "SauceCodePro NF"
style = "Bold Italic"

[font.normal]
family = "SauceCodePro NF"
style = "Medium"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true
save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
startup_mode = "Windowed"

[window.padding]
x = 2
y = 2
